// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYHtOmZH522DsJPKCCBvbgdhypi6TXkM',
    appId: '1:5236353158:web:64fc576dd6065e3bf9c907',
    messagingSenderId: '5236353158',
    projectId: 'amira-860b4',
    authDomain: 'amira-860b4.firebaseapp.com',
    storageBucket: 'amira-860b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4T4BjzW-KEpxAYQkujRzpaWxeKas0A1o',
    appId: '1:5236353158:android:949abc78d3257252f9c907',
    messagingSenderId: '5236353158',
    projectId: 'amira-860b4',
    storageBucket: 'amira-860b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3AN-OY_7Dx478G3BuoG6xizXdrXuB5F4',
    appId: '1:5236353158:ios:3362fe7d5310e33bf9c907',
    messagingSenderId: '5236353158',
    projectId: 'amira-860b4',
    storageBucket: 'amira-860b4.appspot.com',
    iosBundleId: 'com.example.responsiveUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3AN-OY_7Dx478G3BuoG6xizXdrXuB5F4',
    appId: '1:5236353158:ios:3362fe7d5310e33bf9c907',
    messagingSenderId: '5236353158',
    projectId: 'amira-860b4',
    storageBucket: 'amira-860b4.appspot.com',
    iosBundleId: 'com.example.responsiveUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYHtOmZH522DsJPKCCBvbgdhypi6TXkM',
    appId: '1:5236353158:web:52111b3fdbbfd24ff9c907',
    messagingSenderId: '5236353158',
    projectId: 'amira-860b4',
    authDomain: 'amira-860b4.firebaseapp.com',
    storageBucket: 'amira-860b4.appspot.com',
  );
}
